IF(FFMPEG_LIBRARIES AND FFMPEG_INCLUDE_DIR)

	SET(FFMPEG_FOUND TRUE)

ELSE()

	# Use pkg-config to find directories to search in.

	FIND_PACKAGE(PkgConfig)

	IF(PKG_CONFIG_FOUND)
		PKG_CHECK_MODULES(_FFMPEG_AVCODEC libavcodec)
		PKG_CHECK_MODULES(_FFMPEG_AVFORMAT libavformat)
		PKG_CHECK_MODULES(_FFMPEG_AVUTIL libavutil)
	ENDIF()

	# Locate libavcodec.

	FIND_PATH(FFMPEG_AVCODEC_INCLUDE_DIR

		NAMES libavcodec/avcodec.h

		PATHS ${_FFMPEG_AVCODEC_INCLUDE_DIRS}
			/usr/include /usr/local/include

		PATH_SUFFIXES ffmpeg libav

	)

	FIND_LIBRARY(FFMPEG_LIBAVCODEC

		NAMES avcodec
		PATHS ${_FFMPEG_AVCODEC_LIBRARY_DIRS} /usr/lib /usr/local/lib

	)

	# Locate libavformat.

	FIND_LIBRARY(FFMPEG_LIBAVFORMAT

		NAMES avformat
		PATHS ${_FFMPEG_AVFORMAT_LIBRARY_DIRS} /usr/lib /usr/local/lib

	)

	# Locate libavutil.

	FIND_LIBRARY(FFMPEG_LIBAVUTIL

		NAMES avutil
		PATHS ${_FFMPEG_AVUTIL_LIBRARY_DIRS} /usr/lib /usr/local/lib

	)

	# Setup the results of our search.

	IF(FFMPEG_LIBAVCODEC AND FFMPEG_LIBAVFORMAT)
		SET(FFMPEG_FOUND TRUE)
	ENDIF()

	IF(FFMPEG_FOUND)
		SET(FFMPEG_INCLUDE_DIR ${FFMPEG_AVCODEC_INCLUDE_DIR})

		SET(FFMPEG_LIBRARIES

			${FFMPEG_LIBAVCODEC}
			${FFMPEG_LIBAVFORMAT}
			${FFMPEG_LIBAVUTIL}

		)
	ENDIF()

	IF(FFMPEG_FOUND)
		IF(NOT FFMPEG_FIND_QUIETLY)
			MESSAGE(STATUS "Found FFMPEG")
		ENDIF()
	ELSE()
		IF(FFMPEG_FIND_REQUIRED)
			MESSAGE(FATAL_ERROR "Could not find FFMPEG")
		ENDIF()
	ENDIF()

ENDIF()
